/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/test_models/torchbench
/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/fbgemm_gpu_py.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
cuda eval  torchrec_dlrm                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 231, in load_model
    module = importlib.import_module(c)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/__init__.py", line 7, in <module>
    from .data.dlrm_dataloader import get_dataloader
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/canary_models/torchrec_dlrm/data/dlrm_dataloader.py", line 13, in <module>
    from torchrec.datasets.criteo import (
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/__init__.py", line 10, in <module>
    import torchrec.distributed  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/__init__.py", line 38, in <module>
    from torchrec.distributed.model_parallel import DistributedModelParallel  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/model_parallel.py", line 26, in <module>
    from torchrec.distributed.planner import EmbeddingShardingPlanner, Topology
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/__init__.py", line 24, in <module>
    from torchrec.distributed.planner.planners import EmbeddingShardingPlanner  # noqa
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/planners.py", line 21, in <module>
    from torchrec.distributed.planner.constants import BATCH_SIZE, MAX_SIZE
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/planner/constants.py", line 12, in <module>
    from torchrec.distributed.embedding_types import EmbeddingComputeKernel
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/torchrec/distributed/embedding_types.py", line 16, in <module>
    from fbgemm_gpu.split_table_batched_embeddings_ops_training import EmbeddingLocation
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/__init__.py", line 22, in <module>
    import fbgemm_gpu.docs  # noqa: F401, E402
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/__init__.py", line 9, in <module>
    from . import jagged_tensor_ops, table_batched_embedding_ops  # noqa: F401
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/fbgemm_gpu/docs/jagged_tensor_ops.py", line 14, in <module>
    torch.ops.fbgemm.jagged_2d_to_dense,
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/_ops.py", line 1125, in __getattr__
    raise AttributeError(
AttributeError: '_OpNamespace' 'fbgemm' object has no attribute 'jagged_2d_to_dense'

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/test_models/torchbench
cuda eval  BERT_pytorch                       
run_performance_test(): speedup_experiment == True
0.247x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  Background_Matting                 
run_performance_test(): speedup_experiment == True
0.576x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  DALLE2_pytorch                     
run_performance_test(): speedup_experiment == True
0.207x
Op: aten.addmm
Op: aten._scaled_dot_product_efficient_attention
Op: aten.mm
Op: aten.bmm
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  LearningToPaint                    
run_performance_test(): speedup_experiment == True
0.344x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  Super_SloMo                        
run_performance_test(): speedup_experiment == True
0.209x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  alexnet                            
run_performance_test(): speedup_experiment == True
0.768x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  basic_gnn_edgecnn                  
run_performance_test(): speedup_experiment == True
0.597x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  basic_gnn_gcn                      
run_performance_test(): speedup_experiment == True
0.631x
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  basic_gnn_gin                      
run_performance_test(): speedup_experiment == True
0.310x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  basic_gnn_sage                     
run_performance_test(): speedup_experiment == True
0.367x
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  cm3leon_generate                   
run_performance_test(): speedup_experiment == True
0.112x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  dcgan                              
run_performance_test(): speedup_experiment == True
0.541x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  demucs                             
run_performance_test(): speedup_experiment == True
0.736x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  densenet121                        
run_performance_test(): speedup_experiment == True
0.350x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_c4     
run_performance_test(): speedup_experiment == True
0.326x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_dc5    
run_performance_test(): speedup_experiment == True
1.213x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_101_fpn    
run_performance_test(): speedup_experiment == True
0.759x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_c4      
run_performance_test(): speedup_experiment == True
0.893x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_dc5     
run_performance_test(): speedup_experiment == True
0.445x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fasterrcnn_r_50_fpn     
run_performance_test(): speedup_experiment == True
0.603x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_fcos_r_50_fpn           
run_performance_test(): speedup_experiment == True
0.380x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_maskrcnn_r_101_c4       
run_performance_test(): speedup_experiment == True
0.491x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_maskrcnn_r_101_fpn      
run_performance_test(): speedup_experiment == True
0.519x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_maskrcnn_r_50_c4        
run_performance_test(): speedup_experiment == True
0.767x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  detectron2_maskrcnn_r_50_fpn       
run_performance_test(): speedup_experiment == True
0.519x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  dlrm                               
run_performance_test(): speedup_experiment == True
0.416x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  doctr_det_predictor                
run_performance_test(): speedup_experiment == True
0.425x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  doctr_reco_predictor               
run_performance_test(): speedup_experiment == True
0.234x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  drq                                
run_performance_test(): speedup_experiment == True
0.223x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  fastNLP_Bert                       
run_performance_test(): speedup_experiment == True
0.036x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  functorch_dp_cifar10               
run_performance_test(): speedup_experiment == True
0.186x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  functorch_maml_omniglot            
run_performance_test(): speedup_experiment == True
0.208x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Albert                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 986, in forward
    outputs = self.albert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/albert/modeling_albert.py", line 704, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Bart                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1731, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 1587, in forward
    decoder_input_ids = shift_tokens_right(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bart/modeling_bart.py", line 104, in shift_tokens_right
    shifted_input_ids = input_ids.new_zeros(input_ids.shape)
AttributeError: 'str' object has no attribute 'new_zeros'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Bert                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 960, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Bert_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 1360, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/bert/modeling_bert.py", line 960, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_BigBird                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2450, in forward
    outputs = self.bert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/big_bird/modeling_big_bird.py", line 2025, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_DistilBert                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 905, in forward
    dlbrt_output = self.distilbert(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/distilbert/modeling_distilbert.py", line 802, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_GPT2                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_GPT2_large                      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 1074, in forward
    transformer_outputs = self.transformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/gpt2/modeling_gpt2.py", line 776, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Reformer                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2404, in forward
    reformer_outputs = self.reformer(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/reformer/modeling_reformer.py", line 2034, in forward
    self.warn_if_padding_and_no_attention_mask(input_ids, attention_mask)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4169, in warn_if_padding_and_no_attention_mask
    if self.config.pad_token_id in input_ids[:, [-1, 0]]:
TypeError: string indices must be integers

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_T5                              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_T5_base                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_T5_generate                     
run_performance_test(): speedup_experiment == True
0.158x
Op: aten.mm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_T5_large                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1711, in forward
    encoder_outputs = self.encoder(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/t5/modeling_t5.py", line 1010, in forward
    input_shape = input_ids.size()
AttributeError: 'str' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_Whisper                         
run_performance_test(): speedup_experiment == True
0.559x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  hf_distil_whisper                  
run_performance_test(): speedup_experiment == True
0.322x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  lennard_jones                      
run_performance_test(): speedup_experiment == True
0.145x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  llama                              
run_performance_test(): speedup_experiment == True
0.268x
Op: aten.mm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  llama_v2_7b_16h                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 1168, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 966, in forward
    inputs_embeds = self.embed_tokens(input_ids)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/sparse.py", line 163, in forward
    return F.embedding(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/functional.py", line 2266, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not str

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  llava                              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 303, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/llava/__init__.py", line 11, in __init__
    super().__init__(name="llava", test=test, device=device, batch_size=batch_size, extra_args=extra_args)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/framework/huggingface/model_factory.py", line 53, in __init__
    self.model = self.model.to(self.device)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2556, in to
    return super().to(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1173, in to
    return self._apply(convert)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 779, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 804, in _apply
    param_applied = fn(param)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1159, in convert
    return t.to(
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacity of 19.50 GiB of which 43.94 MiB is free. Including non-PyTorch memory, this process has 19.41 GiB memory in use. Of the allocated memory 19.23 GiB is allocated by PyTorch, and 17.44 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  maml                               
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  maml_omniglot                      
run_performance_test(): speedup_experiment == True
0.202x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  microbench_unbacked_tolist_sum     
run_performance_test(): speedup_experiment == True
0.543x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  mnasnet1_0                         
run_performance_test(): speedup_experiment == True
0.154x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  mobilenet_v2                       
run_performance_test(): speedup_experiment == True
0.103x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  mobilenet_v2_quantized_qat         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 303, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/mobilenet_v2_quantized_qat/__init__.py", line 21, in __init__
    raise NotImplementedError("The eval test only supports CPU.")
NotImplementedError: The eval test only supports CPU.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  mobilenet_v3_large                 
run_performance_test(): speedup_experiment == True
0.107x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  moco                               
run_performance_test(): speedup_experiment == True
0.345x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  moondream                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/phi/modeling_phi.py", line 1046, in forward
    outputs = self.model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/transformers/models/phi/modeling_phi.py", line 861, in forward
    batch_size, seq_length = input_ids.shape[:2]
AttributeError: 'str' object has no attribute 'shape'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
number of parameters: 123.69M
num decayed parameter tensors: 50, with 124,354,560 parameters
num non-decayed parameter tensors: 98, with 121,344 parameters
using fused AdamW: True
cuda eval  nanogpt                            
run_performance_test(): speedup_experiment == True
0.164x
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  nvidia_deeprecommender             
run_performance_test(): speedup_experiment == True
0.877x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  opacus_cifar10                     
run_performance_test(): speedup_experiment == True
0.196x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  phlippe_densenet                   
run_performance_test(): speedup_experiment == True
0.164x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  phlippe_resnet                     
run_performance_test(): speedup_experiment == True
0.140x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pyhpc_equation_of_state            
run_performance_test(): speedup_experiment == True
0.966x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pyhpc_isoneutral_mixing            
run_performance_test(): speedup_experiment == True
0.769x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pyhpc_turbulent_kinetic_energy     
run_performance_test(): speedup_experiment == True
0.484x
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pytorch_CycleGAN_and_pix2pix       
run_performance_test(): speedup_experiment == True
0.182x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pytorch_stargan                    
run_performance_test(): speedup_experiment == True
0.410x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  pytorch_unet                       
run_performance_test(): speedup_experiment == True
0.144x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  resnet152                          
run_performance_test(): speedup_experiment == True
0.277x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  resnet18                           
run_performance_test(): speedup_experiment == True
0.129x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  resnet50                           
run_performance_test(): speedup_experiment == True
0.072x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  resnet50_quantized_qat             
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 303, in load_model
    benchmark = benchmark_cls(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/util/model.py", line 38, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/torchbenchmark/torchbenchmark/models/resnet50_quantized_qat/__init__.py", line 21, in __init__
    raise NotImplementedError("The eval test only supports CPU.")
NotImplementedError: The eval test only supports CPU.

model_fail_to_load
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  resnext50_32x4d                    
run_performance_test(): speedup_experiment == True
0.027x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  sam                                
run_performance_test(): speedup_experiment == True
1.476x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
Loading best configs from file /n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/segment_anything_fast/configs/flash_4_configs_a100.p
cuda eval  sam_fast                           
run_performance_test(): speedup_experiment == True
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  shufflenet_v2_x1_0                 
run_performance_test(): speedup_experiment == True
0.144x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  soft_actor_critic                  
run_performance_test(): speedup_experiment == True
0.284x
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  speech_transformer                 
run_performance_test(): speedup_experiment == True
0.181x
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  squeezenet1_1                      
run_performance_test(): speedup_experiment == True
0.151x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  stable_diffusion_text_encoder      
run_performance_test(): speedup_experiment == True
0.164x
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  stable_diffusion_unet              
run_performance_test(): speedup_experiment == True
0.574x
Op: aten.addmm
Op: aten.convolution
Op: aten.mm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_efficientnet                  
run_performance_test(): speedup_experiment == True
0.259x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_regnet                        
run_performance_test(): speedup_experiment == True
0.337x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_resnest                       
run_performance_test(): speedup_experiment == True
0.464x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_vision_transformer            
run_performance_test(): speedup_experiment == True
0.166x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_vision_transformer_large      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2279, in validate_model
    self.model_iter_fn(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 420, in forward_pass
    return mod(*inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 652, in forward
    x = self.forward_features(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 640, in forward_features
    x = self.blocks(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/container.py", line 217, in forward
    input = module(input)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/models/vision_transformer.py", line 156, in forward
    x = x + self.drop_path2(self.ls2(self.mlp(self.norm2(x))))
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/env/lib/python3.10/site-packages/timm/layers/mlp.py", line 42, in forward
    x = self.fc1(x)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/torch/nn/modules/linear.py", line 116, in forward
    return F.linear(input, self.weight, self.bias)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 98.00 MiB. GPU 0 has a total capacity of 19.50 GiB of which 99.94 MiB is free. Including non-PyTorch memory, this process has 19.36 GiB memory in use. Of the allocated memory 19.09 GiB is allocated by PyTorch, and 41.00 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/torchbench.py", line 356, in load_model
    self.validate_model(model, example_inputs)
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 2281, in validate_model
    raise RuntimeError("Eager run failed") from e
RuntimeError: Eager run failed

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  timm_vovnet                        
run_performance_test(): speedup_experiment == True
0.304x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  torch_multimodal_clip              
run_performance_test(): speedup_experiment == True
0.219x
Op: aten.convolution
Op: aten.bmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.addmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  tts_angular                        
run_performance_test(): speedup_experiment == True
0.764x
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  vgg16                              
run_performance_test(): speedup_experiment == True
0.416x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  vision_maskrcnn                    
run_performance_test(): speedup_experiment == True
0.393x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/torchbench
cuda eval  yolov3                             
run_performance_test(): speedup_experiment == True
0.236x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/test_models/torchbench
speedup             gmean=0.00x mean=0.333x
abs_latency         gmean=0.00x mean=180.507x
compilation_latency mean=45.779 seconds
compression_ratio   mean=0.512x
eager_peak_mem      gmean=0.00x mean=0.990x
dynamo_peak_mem     gmean=0.00x mean=1.248x
calls_captured      gmean=0.00x mean=385.447x
unique_graphs       gmean=0.00x mean=5.466x
graph_breaks        gmean=0.00x mean=5.404x
unique_graph_breaks gmean=0.00x mean=2.472x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=0.000x
Finished torchbench-------------------
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  adv_inception_v3                   
run_performance_test(): speedup_experiment == True
0.512x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  beit_base_patch16_224              
run_performance_test(): speedup_experiment == True
0.510x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_efficient_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  botnet26t_256                      
run_performance_test(): speedup_experiment == True
0.325x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  cait_m36_384                       
run_performance_test(): speedup_experiment == True
0.704x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  coat_lite_mini                     
run_performance_test(): speedup_experiment == True
0.521x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  convit_base                        
run_performance_test(): speedup_experiment == True
0.651x
Op: aten.convolution
Op: aten.mm
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  convmixer_768_32                   
run_performance_test(): speedup_experiment == True
0.694x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  convnext_base                      
run_performance_test(): speedup_experiment == True
0.406x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  crossvit_9_240                     
run_performance_test(): speedup_experiment == True
0.441x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  cspdarknet53                       
run_performance_test(): speedup_experiment == True
0.363x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  deit_base_distilled_patch16_224    
run_performance_test(): speedup_experiment == True
0.427x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  dla102                             
run_performance_test(): speedup_experiment == True
0.470x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  dm_nfnet_f0                        
run_performance_test(): speedup_experiment == True
0.639x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  dpn107                             
run_performance_test(): speedup_experiment == True
0.446x
Op: aten.convolution
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  eca_botnext26ts_256                
run_performance_test(): speedup_experiment == True
0.322x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  eca_halonext26ts                   
run_performance_test(): speedup_experiment == True
0.332x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  ese_vovnet19b_dw                   
run_performance_test(): speedup_experiment == True
0.377x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  fbnetc_100                         
run_performance_test(): speedup_experiment == True
0.391x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  fbnetv3_b                          
run_performance_test(): speedup_experiment == True
0.399x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  gernet_l                           
run_performance_test(): speedup_experiment == True
0.365x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  ghostnet_100                       
run_performance_test(): speedup_experiment == True
0.440x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  gluon_inception_v3                 
run_performance_test(): speedup_experiment == True
0.498x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  gmixer_24_224                      
run_performance_test(): speedup_experiment == True
0.520x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  gmlp_s16_224                       
run_performance_test(): speedup_experiment == True
0.486x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  hrnet_w18                          
run_performance_test(): speedup_experiment == True
0.394x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  inception_v3                       
run_performance_test(): speedup_experiment == True
0.512x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  jx_nest_base                       
run_performance_test(): speedup_experiment == True
1.213x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  lcnet_050                          
run_performance_test(): speedup_experiment == True
0.364x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  levit_128                          
run_performance_test(): speedup_experiment == True
0.533x
Op: aten.convolution
Op: aten.bmm
Op: aten.mm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mixer_b16_224                      
run_performance_test(): speedup_experiment == True
0.468x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mixnet_l                           
run_performance_test(): speedup_experiment == True
0.523x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mnasnet_100                        
run_performance_test(): speedup_experiment == True
0.364x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mobilenetv2_100                    
run_performance_test(): speedup_experiment == True
0.342x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mobilenetv3_large_100              
run_performance_test(): speedup_experiment == True
0.381x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  mobilevit_s                        
run_performance_test(): speedup_experiment == True
0.319x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  nfnet_l0                           
run_performance_test(): speedup_experiment == True
0.578x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  pit_b_224                          
run_performance_test(): speedup_experiment == True
0.444x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  pnasnet5large                      
run_performance_test(): speedup_experiment == True
0.457x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  poolformer_m36                     
run_performance_test(): speedup_experiment == True
0.451x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  regnety_002                        
run_performance_test(): speedup_experiment == True
0.361x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  repvgg_a2                          
run_performance_test(): speedup_experiment == True
0.357x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  res2net101_26w_4s                  
run_performance_test(): speedup_experiment == True
0.554x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  res2net50_14w_8s                   
run_performance_test(): speedup_experiment == True
0.541x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  res2next50                         
run_performance_test(): speedup_experiment == True
0.519x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  resmlp_12_224                      
run_performance_test(): speedup_experiment == True
0.483x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  resnest101e                        
run_performance_test(): speedup_experiment == True
0.209x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  rexnet_100                         
run_performance_test(): speedup_experiment == True
0.339x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  sebotnet33ts_256                   
run_performance_test(): speedup_experiment == True
0.433x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  selecsls42b                        
run_performance_test(): speedup_experiment == True
0.467x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  spnasnet_100                       
run_performance_test(): speedup_experiment == True
0.101x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  swin_base_patch4_window7_224       
run_performance_test(): speedup_experiment == True
0.522x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten.mm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  swsl_resnext101_32x16d             
run_performance_test(): speedup_experiment == True
0.500x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  tf_efficientnet_b0                 
run_performance_test(): speedup_experiment == True
0.440x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  tf_mixnet_l                        
run_performance_test(): speedup_experiment == True
0.515x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  tinynet_a                          
run_performance_test(): speedup_experiment == True
0.399x
Op: aten.convolution
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  tnt_s_patch16_224                  
run_performance_test(): speedup_experiment == True
0.619x
Op: aten.convolution
Op: aten.addmm
Op: aten.mm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  twins_pcpvt_base                   
run_performance_test(): speedup_experiment == True
0.428x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  visformer_small                    
run_performance_test(): speedup_experiment == True
0.513x
Op: aten.convolution
Op: aten.bmm
Op: aten.addmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  vit_base_patch16_224               
run_performance_test(): speedup_experiment == True
0.427x
Op: aten.convolution
Op: aten.addmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  volo_d1_224                        
run_performance_test(): speedup_experiment == True
0.617x
Op: aten.convolution
Op: aten.mm
Op: aten.addmm
Op: aten.bmm
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
cuda eval  xcit_large_24_p8_224               
run_performance_test(): speedup_experiment == True
0.555x
Op: aten.convolution
Op: aten.addmm
Op: aten.bmm
Op: aten._scaled_dot_product_flash_attention
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/timm
speedup             gmean=0.51x mean=0.539x
abs_latency         gmean=218.84x mean=250.987x
compilation_latency mean=83.474 seconds
compression_ratio   mean=0.978x
eager_peak_mem      gmean=2.16x mean=3.402x
dynamo_peak_mem     gmean=2.25x mean=3.229x
calls_captured      gmean=516.42x mean=609.089x
unique_graphs       gmean=1.28x mean=1.418x
graph_breaks        gmean=0.00x mean=1.987x
unique_graph_breaks gmean=0.00x mean=1.582x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=0.000x
Finished timm-------------------
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  AlbertForMaskedLM                  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  AlbertForQuestionAnswering         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  AllenaiLongformerBase              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BartForCausalLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BartForConditionalGeneration       
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BertForMaskedLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BertForQuestionAnswering           
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BlenderbotForCausalLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BlenderbotSmallForCausalLM         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  BlenderbotSmallForConditionalGeneration 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  CamemBert                          
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DebertaForMaskedLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DebertaForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DebertaV2ForMaskedLM               
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DebertaV2ForQuestionAnswering      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DistilBertForMaskedLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DistilBertForQuestionAnswering     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  DistillGPT2                        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  ElectraForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  ElectraForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  GPT2ForSequenceClassification      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  GoogleFnet                         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  LayoutLMForMaskedLM                
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  LayoutLMForSequenceClassification  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  M2M100ForConditionalGeneration     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MBartForCausalLM                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MBartForConditionalGeneration      
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MT5ForConditionalGeneration        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MegatronBertForCausalLM            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MegatronBertForQuestionAnswering   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MobileBertForMaskedLM              
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  MobileBertForQuestionAnswering     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  OPTForCausalLM                     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  PLBartForCausalLM                  
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  PLBartForConditionalGeneration     
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  PegasusForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  PegasusForConditionalGeneration    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  RobertaForCausalLM                 
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  RobertaForQuestionAnswering        
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  Speech2Text2ForCausalLM            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  T5ForConditionalGeneration         
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  T5Small                            
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  TrOCRForCausalLM                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  XGLMForCausalLM                    
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  XLNetLMHeadModel                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
cuda eval  YituTechConvBert                   
Traceback (most recent call last):
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/common.py", line 4071, in run
    ) = runner.load_model(
  File "/n/holylabs/LABS/idreos_lab/Users/azhao/pytorch/benchmarks/dynamo/huggingface.py", line 501, in load_model
    for attr in dir(config):
TypeError: 'str' object is not callable

eager_fail_to_run
/n/holylabs/LABS/idreos_lab/Users/azhao/gpu_profiling/data/train_models/huggingface
speedup             gmean=0.00x mean=0.014x
abs_latency         gmean=0.00x mean=15.122x
compilation_latency mean=6.083 seconds
compression_ratio   mean=0.022x
eager_peak_mem      gmean=0.00x mean=0.190x
dynamo_peak_mem     gmean=0.00x mean=0.184x
calls_captured      gmean=0.00x mean=29.660x
unique_graphs       gmean=0.00x mean=0.043x
graph_breaks        gmean=0.00x mean=0.128x
unique_graph_breaks gmean=0.00x mean=0.106x
autograd_captures   gmean=0.00x mean=0.000x
autograd_compiles   gmean=0.00x mean=0.000x
cudagraph_skips     gmean=0.00x mean=0.000x
